chain_width                     = 100
comment_width                   = 100
doc_comment_code_block_width    = 100
error_on_line_overflow          = true
error_on_unformatted            = true
format_code_in_doc_comments     = true
format_macro_matchers           = true
format_strings                  = true
group_imports                   = 'StdExternalCrate'
imports_granularity             = 'Crate'
imports_layout                  = 'HorizontalVertical'
match_arm_blocks                = false
normalize_comments              = true
normalize_doc_attributes        = true
overflow_delimited_expr         = false
reorder_impl_items              = true
struct_field_align_threshold    = 1
tab_spaces                      = 2
trailing_comma                  = 'Never'
use_field_init_shorthand        = true
use_try_shorthand               = true
wrap_comments                   = true
